version: '3'

services:
  island_decor_homepage_django:
    build: ./dockerfiles/island_decor_home_django/
    env_file:
      - ./environment_variables/island_decor_homepage/web_settings.env
      - ./environment_variables/island_decor_homepage/db_settings.env
    expose:
      - "80"
    links:
      - island_decor_homepage_cache
      - island_decor_homepage_database
  island_decor_homepage_database:
    image: postgres:${POSTGRES_VERSION:?err}
    env_file:
      - ./environment_variables/island_decor_homepage/db_settings.env
  island_decor_homepage_cache:
     image: "memcached:${MEMCACHED_VERSION:?err}"
     ports:
       - "11211:11211"
     entrypoint:
      - memcached
      - -m 64
  island_decor_nginx:
    image: nginx:${NGINX_VERSION:?err}
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - island_decor_homepage_django
